### ISSUE TITLE
Market Filter Toggles wiring of API Calls

### ISSUE THREAD

**Issue by wintersummermint** [CryptoBlades/marketplace#11]

**Comment by jnebab** [comment]
Can I have the task details for this? Thanks

**Comment by wintersummermint** [comment]
<img width="266" alt="Screen Shot 2021-08-21 at 3 40 39 A rc="https://user-images.githubusercontent.com/9636557/130285515-90d5379a-5755-41a5-81ea-f335c0825f73.png">

@jnebab  this has dependency on main page UI needed to be built first

**Comment by wintersummermint** [comment]
<img width="257" alt="Screen Shot 2021-08-21 at 3 41 38 AM" src="https://user-images.githubusercontent.com/9636557/130285605-8562481e-1ab5-4be5-90f0-c9491f727889.png">

**Comment by jnebab** [comment]
can I work on that instead? let me know. thanks

**Comment by wintersummermint** [comment]
yes , wait for initial UI though will be available in fewhours

**Comment by jnebab** [comment]
ok sure. thanks
