### ISSUE TITLE
Character Selling Section Page View UI

### ISSUE THREAD

**Issue by wintersummermint** [CryptoBlades/marketplace#14]
<img width="1281" alt="Screen Shot 2021-08-21 at 3 09 54 AM" src="https://user-images.githubusercontent.com/9636557/130282311-23ab5069-9923-444b-b5b6-624725d5e791.png">

**Comment by Mark-AS-Dev** [comment]
Can I work on this? I am happy to help you guys.

**Comment by jnebab** [comment]
is this the UI related to the #11 ? @wintersummermint

**Comment by wintersummermint** [comment]
This is UI only, take it if not taken by @Mark-AS-Dev
