### ISSUE TITLE
Sell Page - Inventory section

### ISSUE THREAD

**Issue by wintersummermint** [CryptoBlades/marketplace#16]

**Comment by wintersummermint** [comment]
<img width="1289" alt="Screen Shot 2021-08-21 at 3 28 04 AM" src="https://user-images.githubusercontent.com/9636557/130284279-5b23031c-d063-421c-ae30-299a3063a1a6.png">

**Comment by nomorecolor** [comment]
@wintersummermint Can I work on this? Happy to help.

**Comment by wintersummermint** [comment]
Thanks, saw your PR

**Comment by wintersummermint** [comment]
![](http://g.recordit.co/AyHp92Wyxo.gif)

Currently having issues on Scroll, can you make sure whole section scrolls down? @nomorecolor

**Comment by Spintacle123** [comment]
need to remove the ads.. based on mockup

**Comment by wintersummermint** [comment]
Ads will persist in the future, we don't want to have view that is 1/4 of screen 

Mockup
![](http://g.recordit.co/l3CyXlgcZD.gif)

**Comment by nomorecolor** [comment]
Sure, will check it.
