### ISSUE TITLE
"Purchase" function to ABI call to contract

### ISSUE THREAD

**Issue by wintersummermint** [CryptoBlades/marketplace#27]

**Comment by bilbolPrime** [comment]
I think we are missing the contract integration all together.
I started working on it on this branch
27market-adding-contracts

The NFTMarket json module needs to be put in the build/contracts folder for this to work properly.

This still needs work but it's a small step in the right direction. I got to read the NFT market contract but stopped integration to get confirmation that this is the right way. However some restructure is needed. I was basically in debug mode and the architecture needs proper review.

Also please note that the API might not work on prod. It's Fire not fire etc... but that's outside the scope of this ticket.

Changes so far (again need rework)
https://github.com/CryptoBlades/marketplace/compare/27market-adding-contracts?expand=1

**Comment by bilbolPrime** [comment]
Imported more contracts and finished, still needs testing, weapon purchase.
Will fill my local chain with weapons and feed the API to test. Couldn't do it with my db because it's filled with live data.

Branch updated with data.

**Comment by bilbolPrime** [comment]
Created draft PR for this issue to start getting eyes and opinions on changes.

Having some stability issues with the contracts being linked (need to refresh and reconnect). Once resolved and purchase weapon finalized, doing the same for other NFTs would be easy.

Almost their.

**Comment by bilbolPrime** [comment]
Live PR opened and awaiting review.
It will allow the purchase of weapons.
