### ISSUE TITLE
MarketPlace Pagination Call

### ISSUE THREAD

**Issue by wintersummermint** [CryptoBlades/marketplace#3]

**Comment by jeffyzxc** [comment]
If no ones working working on this I am happy to help :))

**Comment by jeffyzxc** [comment]
May i know the req/tasks for this? thanks :)

**Comment by jeffyzxc** [comment]
Done with the weapon list.

Will push a separate PR for loading upon changing page and paginated weapon list

**Comment by jeffyzxc** [comment]
BTW is this being fix?

type error 

![image](https://user-images.githubusercontent.com/25240940/135749810-3646424c-fc72-4e4c-9a12-0e4b59125774.png)

**Comment by jeffyzxc** [comment]
I think we need a toaster notif as well so we can display error messages haha
