### ISSUE TITLE
Selling Character list wired to API

### ISSUE THREAD

**Issue by wintersummermint** [CryptoBlades/marketplace#4]

**Comment by jeffyzxc** [comment]
Anyone working on this?

**Comment by jeffyzxc** [comment]
@wintersummermint Is this integration?

**Comment by wintersummermint** [comment]
Yes, this is API wiring up, but i believe no Mockup yet from zhang

**Comment by wintersummermint** [comment]
Ready to Worked on :

<img width="1638" alt="Screen Shot 2021-09-12 at 1 27 53 AM" src="https://user-images.githubusercontent.com/9636557/132956162-597a30fa-4c2e-4bbc-8e41-69de80fc3671.png">

**Comment by jeffyzxc** [comment]
Hi @wintersummermint,

Is the data from the Contract or rest API?

**Comment by jeffyzxc** [comment]
Character stamina is still static will push a diff PR for this
