### ISSUE TITLE
(3-4 hrs) Able to See "My Listings" on Market fetch from API

### ISSUE THREAD

**Issue by wintersummermint** [CryptoBlades/marketplace#73]
Currently its only mockup showing on inventory, let's change it to real data

<img width="1391" alt="Screen Shot 2021-10-29 at 3 09 47 AM" src="https://user-images.githubusercontent.com/9636557/139320194-23f4a09d-a037-43d1-becf-2abd8759644f.png">

My Listing Page Shows :
- Active listings
- Sold Listings
- and not listed

Work needed is to connect to API and fetch inventory and statuses

**Comment by Chriserus** [comment]
@wintersummermint close it if my PR met the requirements
