### ISSUE TITLE
Able to view details of shields in marketplace

### ISSUE THREAD

**Issue by wintersummermint** [CryptoBlades/marketplace#80]
- User should be able to click view and pop up modal 
- Fetch data using ABI call which has pattern you can review inside codebase

<img width="317" alt="Screen Shot 2021-11-06 at 7 43 27 PM" src="https://user-images.githubusercontent.com/9636557/140608395-99b6c0c3-ed71-4efe-8432-6e139e2695a8.png">

Similar to this one
<img width="920" alt="Screen Shot 2021-11-06 at 7 46 08 PM" src="https://user-images.githubusercontent.com/9636557/140608421-e9cff979-e49b-4537-b5eb-6db31b79e33b.png">

**Comment by Chriserus** [comment]
@wintersummermint close this also, if it's done
